namespace QBAPermission;

using SelfLearningCodes_Home.SelfLearningCodes_Home;

permissionset 50000 QBAPermission
{
    Assignable = true;
    Permissions = tabledata "Car Brand"=RIMD,
        tabledata "Car Model"=RIMD,
        tabledata "Sales Header Staging"=RIMD,
        tabledata "Sales Line Staging"=RIMD,
        tabledata "Total Selection Lines"=RIMD,
        table "Car Brand"=X,
        table "Car Model"=X,
        table "Sales Header Staging"=X,
        table "Sales Line Staging"=X,
        table "Total Selection Lines"=X,
        report "Change Pur Cr Memo Post Date"=X,
        report "Change Purchase Posting Date"=X,
        report "Change Sales Posting Date"=X,
        report "Credit Note"=X,
        report "Debit Note"=X,
        report "Delete Customer Ledger Entries"=X,
        report "Delete FA Ledger Entries"=X,
        report "Delete General Ledger Entries"=X,
        report "Delete Vendor Ledger Entries"=X,
        report "Export Sal Cr Memo Into Excel"=X,
        report "Export Sal inv Data Into Excel"=X,
        report "FA Block Delete Report"=X,
        report "Payment Rec. Against Invoice"=X,
        report "Posted Credit Note"=X,
        report "Posted Debit Note"=X,
        report "Posted pur Credit Note"=X,
        report "Posted Voucher_"=X,
        report "Proforma Invoice Backup"=X,
        report "Purchase Report"=X,
        report "Purchase report Archive"=X,
        report "Purchase Report New"=X,
        report Purchase_Register=X,
        report "QBA GSTR-1 File Format"=X,
        report "QBA GSTR_2 File Format"=X,
        report "QBA Posted Sales Credit Memo"=X,
        report "QBA Posted Sales Invoice"=X,
        report "QBA Proforma Invoice"=X,
        report "QBA Purchase Order"=X,
        report "QBA TDS 26Q Export"=X,
        report "Sales Invoice 3"=X,
        report "Sales Invoice Domestic"=X,
        report "Sales Invoice USD"=X,
        report Sales_Register=X,
        report "Update Vendor"=X,
        report UpdateDepBook=X,
        report UpdateGLEntry=X,
        report UpdateGLEntry2=X,
        report UpdateGLEntry3=X,
        report UpdateGLEntry_=X,
        codeunit "Amount In Words"=X,
        codeunit "EventSubscriber for API"=X,
        codeunit "QBA Event Subscriber"=X,
        xmlport "Fixed Asset Xml"=X,
        xmlport Fixed2Asset=X,
        page "API Car Brand"=X,
        page "API Car Model"=X,
        page "CLE Input Box"=X,
        page "For Fixed Asset"=X,
        page "GL List"=X,
        page "Input Box"=X,
        page "QBA Posted Sales Invoices"=X,
        page "QBA Vendor Bank Account List"=X,
        page "QBA Vendor Ledger Entries"=X,
        page "QBAAPIV2 - Attachments"=X,
        page "QBAAPIV2 - Dimension Set Lines"=X,
        page "QBAAPIV2 - Doc Attachments"=X,
        page "QBAAPIV2 - Locations"=X,
        page "QBAAPIV2 - PDF Document"=X,
        page "QBAAPIV2 - Purch Invoice Lines"=X,
        page "QBAAPIV2 - Purch Order Lines"=X,
        page "QBAAPIV2 - Purchase Invoices"=X,
        page "QBAAPIV2 - Purchase Orders"=X,
        page "QBAAPIV2 - Sales Order Lines"=X,
        page "QBAAPIV2 - Sales Orders"=X,
        page "QBAAPIV2 Dimens Values Entity"=X,
        page "Selected Lines Total"=X,
        query "QBA TDS 26Q"=X,
        query QBA_GSTR1B2BQuery=X,
        query QBA_GSTR2B2BQuery=X;
}